name: dpx/banner
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
  - identifier: tx_dpxbanner_file
    type: File
    maxitems: 1
    allowed: gif,png,jpg,jpeg,svg
  - identifier: tx_dpxbanner_link
    type: Link
  - identifier: tx_dpxbanner_link_layout
    type: Select
    renderType: selectSingle
    items:
      - label: 'Interner Link'
        value: internal-link-banner
      - label: 'Externer Link'
        value: external-link-banner
      - label: 'Download'
        value: download-banner
  - identifier: tx_dpxbanner_link_text
    type: Text
    max: 90
  - identifier: tx_dpxbanner_link_background
    type: Select
    renderType: selectSingle
    items:
      - label: 'Gelb'
        value: yellow
      - label: 'Magenta'
        value: magenta
  - identifier: tx_dpxbanner_link_bold
    type: Checkbox
